[platformio]
default_envs = m5stick-c-plus2

[env:m5stick-c-plus2]
platform = espressif32@6.7.0
board = m5stick-c
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    m5stack/M5Unified@0.2.17
    bblanchon/ArduinoJson@7.4.3
