#!/usr/bin/env python3
"""Generate PROGMEM PNG arrays from the pinned airlogos package output."""

from __future__ import annotations

import argparse
import base64
import re
import struct
from pathlib import Path


IATA_CODES = (
    "QF", "JQ", "VA", "NZ", "ZL", "QQ", "3K", "FJ",
    "SQ", "EK", "QR", "EY", "CX", "BA", "UA", "DL", "AA", "AC",
    "JL", "NH", "MH", "TG", "GA", "PR", "LA", "CI", "BR", "CZ",
    "MU", "CA", "KE", "OZ", "VN", "SK", "AY", "KL", "AF", "LH",
    "TK", "FR", "LX", "IB", "TP", "OS", "SN", "EI", "WN", "B6",
    "AS", "HA", "WS", "5X", "FX", "5Y", "PO",
)


def read_pngs(source: Path) -> dict[str, bytes]:
    text = source.read_text(encoding="utf-8")
    entries: dict[str, bytes] = {}
    entry_pattern = re.compile(
        r'^    "([A-Z0-9]{2})": \{\n(.*?)(?=^    "[A-Z0-9]{2}": \{|^\};)',
        re.MULTILINE | re.DOTALL,
    )
    png_pattern = re.compile(r'"png": "data:image/png;base64,([^"]+)"')

    for iata, body in entry_pattern.findall(text):
        match = png_pattern.search(body)
        if match:
            entries[iata] = base64.b64decode(match.group(1))
    return entries


def png_dimensions(data: bytes) -> tuple[int, int]:
    if data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
        raise ValueError("Invalid PNG data")
    return struct.unpack(">II", data[16:24])


def format_array(name: str, data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return (
        f"static const uint8_t {name}[] PROGMEM = {{\n"
        + "\n".join(lines)
        + "\n};\n"
    )


def generate(source: Path, output: Path) -> None:
    pngs = read_pngs(source)
    missing = [code for code in IATA_CODES if code not in pngs]
    if missing:
        raise RuntimeError(f"Missing PNG data for: {', '.join(missing)}")

    parts = [
        "// Generated by tools/generate_airline_logos.py from airlogos 1.0.7.\n",
        "// Do not edit this file manually.\n\n",
    ]
    records = []
    for code in IATA_CODES:
        data = pngs[code]
        width, height = png_dimensions(data)
        symbol = f"logo_{code.lower()}"
        parts.append(format_array(symbol, data))
        records.append(
            f'  {{"{code}", {symbol}, sizeof({symbol}), {width}, {height}}},'
        )

    parts.append("\nstatic const AirlineLogo embeddedAirlineLogos[] = {\n")
    parts.extend(record + "\n" for record in records)
    parts.append("};\n")
    output.write_text("".join(parts), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="Path to airlogos dist/index.js")
    parser.add_argument("output", type=Path, help="Generated .inc output path")
    args = parser.parse_args()
    generate(args.source, args.output)


if __name__ == "__main__":
    main()
